export let stocksInfo = [
  {
    sticker: "APPL",
    companyName: "Apple Inc",
    industry: "Technology",
    shares: 894802319,
    price: 136.72,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "BAC",
    companyName: "Bank of America",
    industry: "Financial",
    shares: 1010100606,
    price: 31.13,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "KO",
    companyName: "The Coca Cola Company",
    industry: "Food",
    shares: 400000000,
    price: 59.99,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "CVX",
    companyName: "Chevron Corp",
    industry: "Oil",
    shares: 161440149,
    price: 144.78,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "AXP",
    companyName: "American Express",
    industry: "Financial",
    shares: 151610700,
    price: 138.62,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "KHC",
    companyName: "Kraft Heinz Co",
    industry: "Food",
    shares: 325634818,
    price: 38.14,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "OXY",
    companyName: "Occidental Petroleum",
    industry: "Oil",
    shares: 158549729,
    price: 58.88,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "MCO",
    companyName: "Moody's Corp",
    industry: "Financial",
    shares: 24669778,
    price: 271.97,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "USB",
    companyName: "U.S Bancorp",
    industry: "TFinancial",
    shares: 119805135,
    price: 46.02,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "ATVI",
    companyName: "Activision Blizzard Inc",
    industry: "Technology",
    shares: 68401150,
    price: 77.86,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "HPQ",
    companyName: "HP Inc",
    industry: "Technology",
    shares: 104476035,
    price: 32.78,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
  {
    sticker: "BK",
    companyName: "Bank of New York Mellon Corp",
    industry: "Technology",
    shares: 72357453,
    price: 41.71,
    directors: { ceo: "Tim Cooks", cfo: "John Snow" },
  },
];
